# Generated by Django 4.0 on 2022-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/cats_photos', verbose_name='Фото'),
        ),
    ]
